### ISSUE TITLE
Link to the output file is broken

### ISSUE THREAD

**Issue by TatianaSelezneva** [tosumitagrawal/testyourskills#3]
Link to the output file is broken in the read.me, it should be 
https://github.com/tosumitagrawal/codingskills/blob/main/output/result_output.csv instead of 
https://github.com/tosumitagrawal/codingskills/blob/main/output/sample_output.csv

**Comment by tosumitagrawal** [comment]
Thanks, It is fixed and input/output data is also simplified.
